### ISSUE TITLE
Event Phrasing

### ISSUE THREAD

**Issue by ferittuncer** [kleros/react-components#18]
https://github.com/kleros/react-components/blob/1950d92fadeb2daab7ca128841bf7567b6cb82e1/src/lib/evidence-timeline.js#L81

Case 302 displays 'Current Ruling' instead of 'Jurors Ruled'. Fix the bug and simplify the logic.

**Comment by ferittuncer** [comment]
This problem happened in execution period but the case was not 'executed'. Logic depends on the case being executed but its better to check whether its in execution period instead.

**Comment by 0xferit** [comment]
Not relevant anymore.
